name: dispatch

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'WinBox Version'
          required: true

permissions:
  packages: write
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install imagemagick to add convert tool used for icon
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    - name: Run Makefile
      run: make all VER=${{ github.event.inputs.version }}
    - name: Save Build as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          *.deb
          dist/
          WinBox
          assets/
    - name: Save Package as Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinBox-${{ github.event.inputs.version }}.deb
        path: WinBox-${{ github.event.inputs.version }}.deb
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.version }}
        name: WinBox ${{ github.event.inputs.version }}
        commit: main
        makeLatest: true
        artifacts: ./WinBox-${{ github.event.inputs.version }}.deb
        artifactContentType: application/vnd.debian.binary-package
        token: ${{ secrets.GITHUB_TOKEN }}